name: Build/release

permissions:
  id-token: write
  contents: write
  attestations: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '20.x'
      
      # Needed to build for windows   
      - name: "Install wine"
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y wine wine32

      - name: Install dependencies
        run: npm install

      - name: Build app
        id: build
        run: npm run build-no-pack

      - name: Package App
        id: pack
        # Package for both windows and linux
        run: npm run electron-pack -- --windows --linux

      - name: Attest build
        id: attestation
        if: steps.build.outcome == 'success'
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/Trakkr Setup *.exe

      - name: Upload files to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Trakkr*.AppImage
            dist/Trakkr Setup *.exe
            ${{ steps.attestation.outputs.bundle-path }}

